//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeArt.DataAccess.Contracts.DbContext.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public string OriginalFileName { get; set; }
        public string StorageFileName { get; set; }
        public string DisplayFileName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public string CreatedBy { get; set; }
        public int FileTypeId { get; set; }
    
        public virtual FileType FileType { get; set; }
    }
}
